/*
 * GENERATED by scripts/extract-emoji-picker.mjs — DO NOT EDIT.
 *
 * Source: the inline picker markup in
 * evidence-dumps/TIER1-fetched/views/page.welcome.html, which the reference's badge editor opens
 * from its `#emoji-picker` button. Six groups, 635 emoji, each a
 * `<span title="name">char</span>`.
 *
 * Regenerate with: pnpm --filter controller emoji:extract
 */
export interface EmojiGroup {
  readonly title: string;
  readonly emoji: readonly { readonly name: string; readonly char: string }[];
}

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
  {
    "title": "Frequently used",
    "emoji": [
      {
        "name": "thumbs_up",
        "char": "👍"
      },
      {
        "name": "-1",
        "char": "👎"
      },
      {
        "name": "sob",
        "char": "😭"
      },
      {
        "name": "fire",
        "char": "🔥"
      },
      {
        "name": "frowning",
        "char": "😦"
      },
      {
        "name": "smile",
        "char": "😄"
      },
      {
        "name": "heart_eyes",
        "char": "😍"
      }
    ]
  },
  {
    "title": "People",
    "emoji": [
      {
        "name": "smile",
        "char": "😄"
      },
      {
        "name": "smiley",
        "char": "😃"
      },
      {
        "name": "grinning",
        "char": "😀"
      },
      {
        "name": "blush",
        "char": "😊"
      },
      {
        "name": "wink",
        "char": "😉"
      },
      {
        "name": "heart_eyes",
        "char": "😍"
      },
      {
        "name": "kissing_heart",
        "char": "😘"
      },
      {
        "name": "kissing_closed_eyes",
        "char": "😚"
      },
      {
        "name": "kissing",
        "char": "😗"
      },
      {
        "name": "kissing_smiling_eyes",
        "char": "😙"
      },
      {
        "name": "stuck_out_tongue_winking_eye",
        "char": "😜"
      },
      {
        "name": "stuck_out_tongue_closed_eyes",
        "char": "😝"
      },
      {
        "name": "stuck_out_tongue",
        "char": "😛"
      },
      {
        "name": "flushed",
        "char": "😳"
      },
      {
        "name": "grin",
        "char": "😁"
      },
      {
        "name": "pensive",
        "char": "😔"
      },
      {
        "name": "relieved",
        "char": "😌"
      },
      {
        "name": "unamused",
        "char": "😒"
      },
      {
        "name": "disappointed",
        "char": "😞"
      },
      {
        "name": "persevere",
        "char": "😣"
      },
      {
        "name": "cry",
        "char": "😢"
      },
      {
        "name": "joy",
        "char": "😂"
      },
      {
        "name": "sob",
        "char": "😭"
      },
      {
        "name": "sleepy",
        "char": "😪"
      },
      {
        "name": "disappointed_relieved",
        "char": "😥"
      },
      {
        "name": "cold_sweat",
        "char": "😰"
      },
      {
        "name": "sweat_smile",
        "char": "😅"
      },
      {
        "name": "sweat",
        "char": "😓"
      },
      {
        "name": "weary",
        "char": "😩"
      },
      {
        "name": "tired_face",
        "char": "😫"
      },
      {
        "name": "fearful",
        "char": "😨"
      },
      {
        "name": "scream",
        "char": "😱"
      },
      {
        "name": "angry",
        "char": "😠"
      },
      {
        "name": "rage",
        "char": "😡"
      },
      {
        "name": "triumph",
        "char": "😤"
      },
      {
        "name": "confounded",
        "char": "😖"
      },
      {
        "name": "laughing",
        "char": "😆"
      },
      {
        "name": "yum",
        "char": "😋"
      },
      {
        "name": "mask",
        "char": "😷"
      },
      {
        "name": "sunglasses",
        "char": "😎"
      },
      {
        "name": "sleeping",
        "char": "😴"
      },
      {
        "name": "dizzy_face",
        "char": "😵"
      },
      {
        "name": "astonished",
        "char": "😲"
      },
      {
        "name": "worried",
        "char": "😟"
      },
      {
        "name": "frowning",
        "char": "😦"
      },
      {
        "name": "anguished",
        "char": "😧"
      },
      {
        "name": "imp",
        "char": "👿"
      },
      {
        "name": "open_mouth",
        "char": "😮"
      },
      {
        "name": "grimacing",
        "char": "😬"
      },
      {
        "name": "neutral_face",
        "char": "😐"
      },
      {
        "name": "confused",
        "char": "😕"
      },
      {
        "name": "hushed",
        "char": "😯"
      },
      {
        "name": "smirk",
        "char": "😏"
      },
      {
        "name": "expressionless",
        "char": "😑"
      },
      {
        "name": "man_with_gua_pi_mao",
        "char": "👲"
      },
      {
        "name": "man_with_turban",
        "char": "👳"
      },
      {
        "name": "cop",
        "char": "👮"
      },
      {
        "name": "construction_worker",
        "char": "👷"
      },
      {
        "name": "guardsman",
        "char": "💂"
      },
      {
        "name": "baby",
        "char": "👶"
      },
      {
        "name": "boy",
        "char": "👦"
      },
      {
        "name": "girl",
        "char": "👧"
      },
      {
        "name": "man",
        "char": "👨"
      },
      {
        "name": "woman",
        "char": "👩"
      },
      {
        "name": "older_man",
        "char": "👴"
      },
      {
        "name": "older_woman",
        "char": "👵"
      },
      {
        "name": "person_with_blond_hair",
        "char": "👱"
      },
      {
        "name": "angel",
        "char": "👼"
      },
      {
        "name": "princess",
        "char": "👸"
      },
      {
        "name": "smiley_cat",
        "char": "😺"
      },
      {
        "name": "smile_cat",
        "char": "😸"
      },
      {
        "name": "heart_eyes_cat",
        "char": "😻"
      },
      {
        "name": "kissing_cat",
        "char": "😽"
      },
      {
        "name": "smirk_cat",
        "char": "😼"
      },
      {
        "name": "scream_cat",
        "char": "🙀"
      },
      {
        "name": "crying_cat_face",
        "char": "😿"
      },
      {
        "name": "joy_cat",
        "char": "😹"
      },
      {
        "name": "pouting_cat",
        "char": "😾"
      },
      {
        "name": "japanese_ogre",
        "char": "👹"
      },
      {
        "name": "japanese_goblin",
        "char": "👺"
      },
      {
        "name": "see_no_evil",
        "char": "🙈"
      },
      {
        "name": "hear_no_evil",
        "char": "🙉"
      },
      {
        "name": "speak_no_evil",
        "char": "🙊"
      },
      {
        "name": "skull",
        "char": "💀"
      },
      {
        "name": "alien",
        "char": "👽"
      },
      {
        "name": "hankey",
        "char": "💩"
      },
      {
        "name": "fire",
        "char": "🔥"
      },
      {
        "name": "sparkles",
        "char": "✨"
      },
      {
        "name": "star2",
        "char": "🌟"
      },
      {
        "name": "dizzy",
        "char": "💫"
      },
      {
        "name": "boom",
        "char": "💥"
      },
      {
        "name": "anger",
        "char": "💢"
      },
      {
        "name": "sweat_drops",
        "char": "💦"
      },
      {
        "name": "droplet",
        "char": "💧"
      },
      {
        "name": "zzz",
        "char": "💤"
      },
      {
        "name": "dash",
        "char": "💨"
      },
      {
        "name": "ear",
        "char": "👂"
      },
      {
        "name": "eyes",
        "char": "👀"
      },
      {
        "name": "nose",
        "char": "👃"
      },
      {
        "name": "tongue",
        "char": "👅"
      },
      {
        "name": "lips",
        "char": "👄"
      },
      {
        "name": "thumbs_up",
        "char": "👍"
      },
      {
        "name": "-1",
        "char": "👎"
      },
      {
        "name": "ok_hand",
        "char": "👌"
      },
      {
        "name": "facepunch",
        "char": "👊"
      },
      {
        "name": "fist",
        "char": "✊"
      },
      {
        "name": "wave",
        "char": "👋"
      },
      {
        "name": "hand",
        "char": "✋"
      },
      {
        "name": "open_hands",
        "char": "👐"
      },
      {
        "name": "point_up_2",
        "char": "👆"
      },
      {
        "name": "point_down",
        "char": "👇"
      },
      {
        "name": "point_right",
        "char": "👉"
      },
      {
        "name": "point_left",
        "char": "👈"
      },
      {
        "name": "raised_hands",
        "char": "🙌"
      },
      {
        "name": "pray",
        "char": "🙏"
      },
      {
        "name": "clap",
        "char": "👏"
      },
      {
        "name": "muscle",
        "char": "💪"
      },
      {
        "name": "walking",
        "char": "🚶"
      },
      {
        "name": "runner",
        "char": "🏃"
      },
      {
        "name": "dancer",
        "char": "💃"
      },
      {
        "name": "couple",
        "char": "👫"
      },
      {
        "name": "family",
        "char": "👪"
      },
      {
        "name": "couplekiss",
        "char": "💏"
      },
      {
        "name": "couple_with_heart",
        "char": "💑"
      },
      {
        "name": "dancers",
        "char": "👯"
      },
      {
        "name": "ok_woman",
        "char": "🙆"
      },
      {
        "name": "no_good",
        "char": "🙅"
      },
      {
        "name": "information_desk_person",
        "char": "💁"
      },
      {
        "name": "raising_hand",
        "char": "🙋"
      },
      {
        "name": "massage",
        "char": "💆"
      },
      {
        "name": "haircut",
        "char": "💇"
      },
      {
        "name": "nail_care",
        "char": "💅"
      },
      {
        "name": "bride_with_veil",
        "char": "👰"
      },
      {
        "name": "person_with_pouting_face",
        "char": "🙎"
      },
      {
        "name": "person_frowning",
        "char": "🙍"
      },
      {
        "name": "bow",
        "char": "🙇"
      },
      {
        "name": "tophat",
        "char": "🎩"
      },
      {
        "name": "crown",
        "char": "👑"
      },
      {
        "name": "womans_hat",
        "char": "👒"
      },
      {
        "name": "athletic_shoe",
        "char": "👟"
      },
      {
        "name": "mans_shoe",
        "char": "👞"
      },
      {
        "name": "sandal",
        "char": "👡"
      },
      {
        "name": "high_heel",
        "char": "👠"
      },
      {
        "name": "boot",
        "char": "👢"
      },
      {
        "name": "shirt",
        "char": "👕"
      },
      {
        "name": "necktie",
        "char": "👔"
      },
      {
        "name": "womans_clothes",
        "char": "👚"
      },
      {
        "name": "dress",
        "char": "👗"
      },
      {
        "name": "running_shirt_with_sash",
        "char": "🎽"
      },
      {
        "name": "jeans",
        "char": "👖"
      },
      {
        "name": "kimono",
        "char": "👘"
      },
      {
        "name": "bikini",
        "char": "👙"
      },
      {
        "name": "briefcase",
        "char": "💼"
      },
      {
        "name": "handbag",
        "char": "👜"
      },
      {
        "name": "pouch",
        "char": "👝"
      },
      {
        "name": "purse",
        "char": "👛"
      },
      {
        "name": "eyeglasses",
        "char": "👓"
      },
      {
        "name": "ribbon",
        "char": "🎀"
      },
      {
        "name": "closed_umbrella",
        "char": "🌂"
      },
      {
        "name": "lipstick",
        "char": "💄"
      },
      {
        "name": "yellow_heart",
        "char": "💛"
      },
      {
        "name": "blue_heart",
        "char": "💙"
      },
      {
        "name": "purple_heart",
        "char": "💜"
      },
      {
        "name": "green_heart",
        "char": "💚"
      },
      {
        "name": "broken_heart",
        "char": "💔"
      },
      {
        "name": "heartpulse",
        "char": "💗"
      },
      {
        "name": "heartbeat",
        "char": "💓"
      },
      {
        "name": "two_hearts",
        "char": "💕"
      },
      {
        "name": "sparkling_heart",
        "char": "💖"
      },
      {
        "name": "revolving_hearts",
        "char": "💞"
      },
      {
        "name": "cupid",
        "char": "💘"
      },
      {
        "name": "love_letter",
        "char": "💌"
      },
      {
        "name": "kiss",
        "char": "💋"
      },
      {
        "name": "ring",
        "char": "💍"
      },
      {
        "name": "gem",
        "char": "💎"
      },
      {
        "name": "bust_in_silhouette",
        "char": "👤"
      },
      {
        "name": "speech_balloon",
        "char": "💬"
      },
      {
        "name": "footprints",
        "char": "👣"
      }
    ]
  },
  {
    "title": "Nature",
    "emoji": [
      {
        "name": "dog",
        "char": "🐶"
      },
      {
        "name": "wolf",
        "char": "🐺"
      },
      {
        "name": "cat",
        "char": "🐱"
      },
      {
        "name": "mouse",
        "char": "🐭"
      },
      {
        "name": "hamster",
        "char": "🐹"
      },
      {
        "name": "rabbit",
        "char": "🐰"
      },
      {
        "name": "frog",
        "char": "🐸"
      },
      {
        "name": "tiger",
        "char": "🐯"
      },
      {
        "name": "koala",
        "char": "🐨"
      },
      {
        "name": "bear",
        "char": "🐻"
      },
      {
        "name": "pig",
        "char": "🐷"
      },
      {
        "name": "pig_nose",
        "char": "🐽"
      },
      {
        "name": "cow",
        "char": "🐮"
      },
      {
        "name": "boar",
        "char": "🐗"
      },
      {
        "name": "monkey_face",
        "char": "🐵"
      },
      {
        "name": "monkey",
        "char": "🐒"
      },
      {
        "name": "horse",
        "char": "🐴"
      },
      {
        "name": "sheep",
        "char": "🐑"
      },
      {
        "name": "elephant",
        "char": "🐘"
      },
      {
        "name": "panda_face",
        "char": "🐼"
      },
      {
        "name": "penguin",
        "char": "🐧"
      },
      {
        "name": "bird",
        "char": "🐦"
      },
      {
        "name": "baby_chick",
        "char": "🐤"
      },
      {
        "name": "hatched_chick",
        "char": "🐥"
      },
      {
        "name": "hatching_chick",
        "char": "🐣"
      },
      {
        "name": "chicken",
        "char": "🐔"
      },
      {
        "name": "snake",
        "char": "🐍"
      },
      {
        "name": "turtle",
        "char": "🐢"
      },
      {
        "name": "bug",
        "char": "🐛"
      },
      {
        "name": "bee",
        "char": "🐝"
      },
      {
        "name": "ant",
        "char": "🐜"
      },
      {
        "name": "beetle",
        "char": "🐞"
      },
      {
        "name": "snail",
        "char": "🐌"
      },
      {
        "name": "octopus",
        "char": "🐙"
      },
      {
        "name": "shell",
        "char": "🐚"
      },
      {
        "name": "tropical_fish",
        "char": "🐠"
      },
      {
        "name": "fish",
        "char": "🐟"
      },
      {
        "name": "dolphin",
        "char": "🐬"
      },
      {
        "name": "whale",
        "char": "🐳"
      },
      {
        "name": "racehorse",
        "char": "🐎"
      },
      {
        "name": "dragon_face",
        "char": "🐲"
      },
      {
        "name": "blowfish",
        "char": "🐡"
      },
      {
        "name": "camel",
        "char": "🐫"
      },
      {
        "name": "poodle",
        "char": "🐩"
      },
      {
        "name": "feet",
        "char": "🐾"
      },
      {
        "name": "bouquet",
        "char": "💐"
      },
      {
        "name": "cherry_blossom",
        "char": "🌸"
      },
      {
        "name": "tulip",
        "char": "🌷"
      },
      {
        "name": "four_leaf_clover",
        "char": "🍀"
      },
      {
        "name": "rose",
        "char": "🌹"
      },
      {
        "name": "sunflower",
        "char": "🌻"
      },
      {
        "name": "hibiscus",
        "char": "🌺"
      },
      {
        "name": "maple_leaf",
        "char": "🍁"
      },
      {
        "name": "leaves",
        "char": "🍃"
      },
      {
        "name": "fallen_leaf",
        "char": "🍂"
      },
      {
        "name": "herb",
        "char": "🌿"
      },
      {
        "name": "ear_of_rice",
        "char": "🌾"
      },
      {
        "name": "mushroom",
        "char": "🍄"
      },
      {
        "name": "cactus",
        "char": "🌵"
      },
      {
        "name": "palm_tree",
        "char": "🌴"
      },
      {
        "name": "chestnut",
        "char": "🌰"
      },
      {
        "name": "seedling",
        "char": "🌱"
      },
      {
        "name": "blossom",
        "char": "🌼"
      },
      {
        "name": "new_moon",
        "char": "🌑"
      },
      {
        "name": "first_quarter_moon",
        "char": "🌓"
      },
      {
        "name": "moon",
        "char": "🌔"
      },
      {
        "name": "full_moon",
        "char": "🌕"
      },
      {
        "name": "first_quarter_moon_with_face",
        "char": "🌛"
      },
      {
        "name": "crescent_moon",
        "char": "🌙"
      },
      {
        "name": "earth_asia",
        "char": "🌏"
      },
      {
        "name": "volcano",
        "char": "🌋"
      },
      {
        "name": "milky_way",
        "char": "🌌"
      },
      {
        "name": "stars",
        "char": "🌠"
      },
      {
        "name": "partly_sunny",
        "char": "⛅"
      },
      {
        "name": "snowman",
        "char": "⛄"
      },
      {
        "name": "cyclone",
        "char": "🌀"
      },
      {
        "name": "foggy",
        "char": "🌁"
      },
      {
        "name": "rainbow",
        "char": "🌈"
      },
      {
        "name": "ocean",
        "char": "🌊"
      }
    ]
  },
  {
    "title": "Objects",
    "emoji": [
      {
        "name": "bamboo",
        "char": "🎍"
      },
      {
        "name": "gift_heart",
        "char": "💝"
      },
      {
        "name": "dolls",
        "char": "🎎"
      },
      {
        "name": "school_satchel",
        "char": "🎒"
      },
      {
        "name": "mortar_board",
        "char": "🎓"
      },
      {
        "name": "flags",
        "char": "🎏"
      },
      {
        "name": "fireworks",
        "char": "🎆"
      },
      {
        "name": "sparkler",
        "char": "🎇"
      },
      {
        "name": "wind_chime",
        "char": "🎐"
      },
      {
        "name": "rice_scene",
        "char": "🎑"
      },
      {
        "name": "jack_o_lantern",
        "char": "🎃"
      },
      {
        "name": "ghost",
        "char": "👻"
      },
      {
        "name": "santa",
        "char": "🎅"
      },
      {
        "name": "christmas_tree",
        "char": "🎄"
      },
      {
        "name": "gift",
        "char": "🎁"
      },
      {
        "name": "tanabata_tree",
        "char": "🎋"
      },
      {
        "name": "tada",
        "char": "🎉"
      },
      {
        "name": "confetti_ball",
        "char": "🎊"
      },
      {
        "name": "balloon",
        "char": "🎈"
      },
      {
        "name": "crossed_flags",
        "char": "🎌"
      },
      {
        "name": "crystal_ball",
        "char": "🔮"
      },
      {
        "name": "movie_camera",
        "char": "🎥"
      },
      {
        "name": "camera",
        "char": "📷"
      },
      {
        "name": "video_camera",
        "char": "📹"
      },
      {
        "name": "vhs",
        "char": "📼"
      },
      {
        "name": "cd",
        "char": "💿"
      },
      {
        "name": "dvd",
        "char": "📀"
      },
      {
        "name": "minidisc",
        "char": "💽"
      },
      {
        "name": "floppy_disk",
        "char": "💾"
      },
      {
        "name": "computer",
        "char": "💻"
      },
      {
        "name": "iphone",
        "char": "📱"
      },
      {
        "name": "telephone_receiver",
        "char": "📞"
      },
      {
        "name": "pager",
        "char": "📟"
      },
      {
        "name": "fax",
        "char": "📠"
      },
      {
        "name": "satellite",
        "char": "📡"
      },
      {
        "name": "tv",
        "char": "📺"
      },
      {
        "name": "radio",
        "char": "📻"
      },
      {
        "name": "loud_sound",
        "char": "🔊"
      },
      {
        "name": "bell",
        "char": "🔔"
      },
      {
        "name": "loudspeaker",
        "char": "📢"
      },
      {
        "name": "mega",
        "char": "📣"
      },
      {
        "name": "hourglass_flowing_sand",
        "char": "⏳"
      },
      {
        "name": "hourglass",
        "char": "⌛"
      },
      {
        "name": "alarm_clock",
        "char": "⏰"
      },
      {
        "name": "watch",
        "char": "⌚"
      },
      {
        "name": "unlock",
        "char": "🔓"
      },
      {
        "name": "lock",
        "char": "🔒"
      },
      {
        "name": "lock_with_ink_pen",
        "char": "🔏"
      },
      {
        "name": "closed_lock_with_key",
        "char": "🔐"
      },
      {
        "name": "key",
        "char": "🔑"
      },
      {
        "name": "mag_right",
        "char": "🔎"
      },
      {
        "name": "bulb",
        "char": "💡"
      },
      {
        "name": "flashlight",
        "char": "🔦"
      },
      {
        "name": "electric_plug",
        "char": "🔌"
      },
      {
        "name": "battery",
        "char": "🔋"
      },
      {
        "name": "mag",
        "char": "🔍"
      },
      {
        "name": "bath",
        "char": "🛀"
      },
      {
        "name": "toilet",
        "char": "🚽"
      },
      {
        "name": "wrench",
        "char": "🔧"
      },
      {
        "name": "nut_and_bolt",
        "char": "🔩"
      },
      {
        "name": "hammer",
        "char": "🔨"
      },
      {
        "name": "door",
        "char": "🚪"
      },
      {
        "name": "smoking",
        "char": "🚬"
      },
      {
        "name": "bomb",
        "char": "💣"
      },
      {
        "name": "gun",
        "char": "🔫"
      },
      {
        "name": "hocho",
        "char": "🔪"
      },
      {
        "name": "pill",
        "char": "💊"
      },
      {
        "name": "syringe",
        "char": "💉"
      },
      {
        "name": "moneybag",
        "char": "💰"
      },
      {
        "name": "yen",
        "char": "💴"
      },
      {
        "name": "dollar",
        "char": "💵"
      },
      {
        "name": "credit_card",
        "char": "💳"
      },
      {
        "name": "money_with_wings",
        "char": "💸"
      },
      {
        "name": "calling",
        "char": "📲"
      },
      {
        "name": "e-mail",
        "char": "📧"
      },
      {
        "name": "inbox_tray",
        "char": "📥"
      },
      {
        "name": "outbox_tray",
        "char": "📤"
      },
      {
        "name": "envelope_with_arrow",
        "char": "📩"
      },
      {
        "name": "incoming_envelope",
        "char": "📨"
      },
      {
        "name": "mailbox",
        "char": "📫"
      },
      {
        "name": "mailbox_closed",
        "char": "📪"
      },
      {
        "name": "postbox",
        "char": "📮"
      },
      {
        "name": "package",
        "char": "📦"
      },
      {
        "name": "memo",
        "char": "📝"
      },
      {
        "name": "page_facing_up",
        "char": "📄"
      },
      {
        "name": "page_with_curl",
        "char": "📃"
      },
      {
        "name": "bookmark_tabs",
        "char": "📑"
      },
      {
        "name": "bar_chart",
        "char": "📊"
      },
      {
        "name": "chart_with_upwards_trend",
        "char": "📈"
      },
      {
        "name": "chart_with_downwards_trend",
        "char": "📉"
      },
      {
        "name": "scroll",
        "char": "📜"
      },
      {
        "name": "clipboard",
        "char": "📋"
      },
      {
        "name": "date",
        "char": "📅"
      },
      {
        "name": "calendar",
        "char": "📆"
      },
      {
        "name": "card_index",
        "char": "📇"
      },
      {
        "name": "file_folder",
        "char": "📁"
      },
      {
        "name": "open_file_folder",
        "char": "📂"
      },
      {
        "name": "pushpin",
        "char": "📌"
      },
      {
        "name": "paperclip",
        "char": "📎"
      },
      {
        "name": "straight_ruler",
        "char": "📏"
      },
      {
        "name": "triangular_ruler",
        "char": "📐"
      },
      {
        "name": "closed_book",
        "char": "📕"
      },
      {
        "name": "green_book",
        "char": "📗"
      },
      {
        "name": "blue_book",
        "char": "📘"
      },
      {
        "name": "orange_book",
        "char": "📙"
      },
      {
        "name": "notebook",
        "char": "📓"
      },
      {
        "name": "notebook_with_decorative_cover",
        "char": "📔"
      },
      {
        "name": "ledger",
        "char": "📒"
      },
      {
        "name": "books",
        "char": "📚"
      },
      {
        "name": "book",
        "char": "📖"
      },
      {
        "name": "bookmark",
        "char": "🔖"
      },
      {
        "name": "name_badge",
        "char": "📛"
      },
      {
        "name": "newspaper",
        "char": "📰"
      },
      {
        "name": "art",
        "char": "🎨"
      },
      {
        "name": "clapper",
        "char": "🎬"
      },
      {
        "name": "microphone",
        "char": "🎤"
      },
      {
        "name": "headphones",
        "char": "🎧"
      },
      {
        "name": "musical_score",
        "char": "🎼"
      },
      {
        "name": "musical_note",
        "char": "🎵"
      },
      {
        "name": "notes",
        "char": "🎶"
      },
      {
        "name": "musical_keyboard",
        "char": "🎹"
      },
      {
        "name": "violin",
        "char": "🎻"
      },
      {
        "name": "trumpet",
        "char": "🎺"
      },
      {
        "name": "saxophone",
        "char": "🎷"
      },
      {
        "name": "guitar",
        "char": "🎸"
      },
      {
        "name": "space_invader",
        "char": "👾"
      },
      {
        "name": "video_game",
        "char": "🎮"
      },
      {
        "name": "black_joker",
        "char": "🃏"
      },
      {
        "name": "flower_playing_cards",
        "char": "🎴"
      },
      {
        "name": "mahjong",
        "char": "🀄"
      },
      {
        "name": "game_die",
        "char": "🎲"
      },
      {
        "name": "dart",
        "char": "🎯"
      },
      {
        "name": "football",
        "char": "🏈"
      },
      {
        "name": "basketball",
        "char": "🏀"
      },
      {
        "name": "soccer",
        "char": "⚽"
      },
      {
        "name": "baseball",
        "char": "⚾"
      },
      {
        "name": "tennis",
        "char": "🎾"
      },
      {
        "name": "8ball",
        "char": "🎱"
      },
      {
        "name": "bowling",
        "char": "🎳"
      },
      {
        "name": "golf",
        "char": "⛳"
      },
      {
        "name": "checkered_flag",
        "char": "🏁"
      },
      {
        "name": "trophy",
        "char": "🏆"
      },
      {
        "name": "ski",
        "char": "🎿"
      },
      {
        "name": "snowboarder",
        "char": "🏂"
      },
      {
        "name": "swimmer",
        "char": "🏊"
      },
      {
        "name": "surfer",
        "char": "🏄"
      },
      {
        "name": "fishing_pole_and_fish",
        "char": "🎣"
      },
      {
        "name": "tea",
        "char": "🍵"
      },
      {
        "name": "sake",
        "char": "🍶"
      },
      {
        "name": "beer",
        "char": "🍺"
      },
      {
        "name": "beers",
        "char": "🍻"
      },
      {
        "name": "cocktail",
        "char": "🍸"
      },
      {
        "name": "tropical_drink",
        "char": "🍹"
      },
      {
        "name": "wine_glass",
        "char": "🍷"
      },
      {
        "name": "fork_and_knife",
        "char": "🍴"
      },
      {
        "name": "pizza",
        "char": "🍕"
      },
      {
        "name": "hamburger",
        "char": "🍔"
      },
      {
        "name": "fries",
        "char": "🍟"
      },
      {
        "name": "poultry_leg",
        "char": "🍗"
      },
      {
        "name": "meat_on_bone",
        "char": "🍖"
      },
      {
        "name": "spaghetti",
        "char": "🍝"
      },
      {
        "name": "curry",
        "char": "🍛"
      },
      {
        "name": "fried_shrimp",
        "char": "🍤"
      },
      {
        "name": "bento",
        "char": "🍱"
      },
      {
        "name": "sushi",
        "char": "🍣"
      },
      {
        "name": "fish_cake",
        "char": "🍥"
      },
      {
        "name": "rice_ball",
        "char": "🍙"
      },
      {
        "name": "rice_cracker",
        "char": "🍘"
      },
      {
        "name": "rice",
        "char": "🍚"
      },
      {
        "name": "ramen",
        "char": "🍜"
      },
      {
        "name": "stew",
        "char": "🍲"
      },
      {
        "name": "oden",
        "char": "🍢"
      },
      {
        "name": "dango",
        "char": "🍡"
      },
      {
        "name": "egg",
        "char": "🍳"
      },
      {
        "name": "bread",
        "char": "🍞"
      },
      {
        "name": "doughnut",
        "char": "🍩"
      },
      {
        "name": "custard",
        "char": "🍮"
      },
      {
        "name": "icecream",
        "char": "🍦"
      },
      {
        "name": "ice_cream",
        "char": "🍨"
      },
      {
        "name": "shaved_ice",
        "char": "🍧"
      },
      {
        "name": "birthday",
        "char": "🎂"
      },
      {
        "name": "cake",
        "char": "🍰"
      },
      {
        "name": "cookie",
        "char": "🍪"
      },
      {
        "name": "chocolate_bar",
        "char": "🍫"
      },
      {
        "name": "candy",
        "char": "🍬"
      },
      {
        "name": "lollipop",
        "char": "🍭"
      },
      {
        "name": "honey_pot",
        "char": "🍯"
      },
      {
        "name": "apple",
        "char": "🍎"
      },
      {
        "name": "green_apple",
        "char": "🍏"
      },
      {
        "name": "tangerine",
        "char": "🍊"
      },
      {
        "name": "cherries",
        "char": "🍒"
      },
      {
        "name": "grapes",
        "char": "🍇"
      },
      {
        "name": "watermelon",
        "char": "🍉"
      },
      {
        "name": "strawberry",
        "char": "🍓"
      },
      {
        "name": "peach",
        "char": "🍑"
      },
      {
        "name": "melon",
        "char": "🍈"
      },
      {
        "name": "banana",
        "char": "🍌"
      },
      {
        "name": "pineapple",
        "char": "🍍"
      },
      {
        "name": "sweet_potato",
        "char": "🍠"
      },
      {
        "name": "eggplant",
        "char": "🍆"
      },
      {
        "name": "tomato",
        "char": "🍅"
      },
      {
        "name": "corn",
        "char": "🌽"
      }
    ]
  },
  {
    "title": "Places",
    "emoji": [
      {
        "name": "house",
        "char": "🏠"
      },
      {
        "name": "house_with_garden",
        "char": "🏡"
      },
      {
        "name": "school",
        "char": "🏫"
      },
      {
        "name": "office",
        "char": "🏢"
      },
      {
        "name": "post_office",
        "char": "🏣"
      },
      {
        "name": "hospital",
        "char": "🏥"
      },
      {
        "name": "bank",
        "char": "🏦"
      },
      {
        "name": "convenience_store",
        "char": "🏪"
      },
      {
        "name": "love_hotel",
        "char": "🏩"
      },
      {
        "name": "hotel",
        "char": "🏨"
      },
      {
        "name": "wedding",
        "char": "💒"
      },
      {
        "name": "church",
        "char": "⛪"
      },
      {
        "name": "department_store",
        "char": "🏬"
      },
      {
        "name": "city_sunrise",
        "char": "🌇"
      },
      {
        "name": "city_sunset",
        "char": "🌆"
      },
      {
        "name": "japanese_castle",
        "char": "🏯"
      },
      {
        "name": "european_castle",
        "char": "🏰"
      },
      {
        "name": "tent",
        "char": "⛺"
      },
      {
        "name": "factory",
        "char": "🏭"
      },
      {
        "name": "tokyo_tower",
        "char": "🗼"
      },
      {
        "name": "japan",
        "char": "🗾"
      },
      {
        "name": "mount_fuji",
        "char": "🗻"
      },
      {
        "name": "sunrise_over_mountains",
        "char": "🌄"
      },
      {
        "name": "sunrise",
        "char": "🌅"
      },
      {
        "name": "night_with_stars",
        "char": "🌃"
      },
      {
        "name": "statue_of_liberty",
        "char": "🗽"
      },
      {
        "name": "bridge_at_night",
        "char": "🌉"
      },
      {
        "name": "carousel_horse",
        "char": "🎠"
      },
      {
        "name": "ferris_wheel",
        "char": "🎡"
      },
      {
        "name": "fountain",
        "char": "⛲"
      },
      {
        "name": "roller_coaster",
        "char": "🎢"
      },
      {
        "name": "ship",
        "char": "🚢"
      },
      {
        "name": "boat",
        "char": "⛵"
      },
      {
        "name": "speedboat",
        "char": "🚤"
      },
      {
        "name": "rocket",
        "char": "🚀"
      },
      {
        "name": "seat",
        "char": "💺"
      },
      {
        "name": "station",
        "char": "🚉"
      },
      {
        "name": "bullettrain_side",
        "char": "🚄"
      },
      {
        "name": "bullettrain_front",
        "char": "🚅"
      },
      {
        "name": "metro",
        "char": "🚇"
      },
      {
        "name": "railway_car",
        "char": "🚃"
      },
      {
        "name": "bus",
        "char": "🚌"
      },
      {
        "name": "blue_car",
        "char": "🚙"
      },
      {
        "name": "car",
        "char": "🚗"
      },
      {
        "name": "taxi",
        "char": "🚕"
      },
      {
        "name": "truck",
        "char": "🚚"
      },
      {
        "name": "rotating_light",
        "char": "🚨"
      },
      {
        "name": "police_car",
        "char": "🚓"
      },
      {
        "name": "fire_engine",
        "char": "🚒"
      },
      {
        "name": "ambulance",
        "char": "🚑"
      },
      {
        "name": "bike",
        "char": "🚲"
      },
      {
        "name": "barber",
        "char": "💈"
      },
      {
        "name": "busstop",
        "char": "🚏"
      },
      {
        "name": "ticket",
        "char": "🎫"
      },
      {
        "name": "traffic_light",
        "char": "🚥"
      },
      {
        "name": "construction",
        "char": "🚧"
      },
      {
        "name": "beginner",
        "char": "🔰"
      },
      {
        "name": "fuelpump",
        "char": "⛽"
      },
      {
        "name": "izakaya_lantern",
        "char": "🏮"
      },
      {
        "name": "slot_machine",
        "char": "🎰"
      },
      {
        "name": "moyai",
        "char": "🗿"
      },
      {
        "name": "circus_tent",
        "char": "🎪"
      },
      {
        "name": "performing_arts",
        "char": "🎭"
      },
      {
        "name": "round_pushpin",
        "char": "📍"
      },
      {
        "name": "triangular_flag_on_post",
        "char": "🚩"
      }
    ]
  },
  {
    "title": "Symbols",
    "emoji": [
      {
        "name": "keycap_ten",
        "char": "🔟"
      },
      {
        "name": "1234",
        "char": "🔢"
      },
      {
        "name": "symbols",
        "char": "🔣"
      },
      {
        "name": "capital_abcd",
        "char": "🔠"
      },
      {
        "name": "abcd",
        "char": "🔡"
      },
      {
        "name": "abc",
        "char": "🔤"
      },
      {
        "name": "arrow_up_small",
        "char": "🔼"
      },
      {
        "name": "arrow_down_small",
        "char": "🔽"
      },
      {
        "name": "rewind",
        "char": "⏪"
      },
      {
        "name": "fast_forward",
        "char": "⏩"
      },
      {
        "name": "arrow_double_up",
        "char": "⏫"
      },
      {
        "name": "arrow_double_down",
        "char": "⏬"
      },
      {
        "name": "ok",
        "char": "🆗"
      },
      {
        "name": "new",
        "char": "🆕"
      },
      {
        "name": "up",
        "char": "🆙"
      },
      {
        "name": "cool",
        "char": "🆒"
      },
      {
        "name": "free",
        "char": "🆓"
      },
      {
        "name": "ng",
        "char": "🆖"
      },
      {
        "name": "signal_strength",
        "char": "📶"
      },
      {
        "name": "cinema",
        "char": "🎦"
      },
      {
        "name": "koko",
        "char": "🈁"
      },
      {
        "name": "u6307",
        "char": "🈯"
      },
      {
        "name": "u7a7a",
        "char": "🈳"
      },
      {
        "name": "u6e80",
        "char": "🈵"
      },
      {
        "name": "u5408",
        "char": "🈴"
      },
      {
        "name": "u7981",
        "char": "🈲"
      },
      {
        "name": "ideograph_advantage",
        "char": "🉐"
      },
      {
        "name": "u5272",
        "char": "🈹"
      },
      {
        "name": "u55b6",
        "char": "🈺"
      },
      {
        "name": "u6709",
        "char": "🈶"
      },
      {
        "name": "u7121",
        "char": "🈚"
      },
      {
        "name": "restroom",
        "char": "🚻"
      },
      {
        "name": "mens",
        "char": "🚹"
      },
      {
        "name": "womens",
        "char": "🚺"
      },
      {
        "name": "baby_symbol",
        "char": "🚼"
      },
      {
        "name": "wc",
        "char": "🚾"
      },
      {
        "name": "no_smoking",
        "char": "🚭"
      },
      {
        "name": "u7533",
        "char": "🈸"
      },
      {
        "name": "accept",
        "char": "🉑"
      },
      {
        "name": "cl",
        "char": "🆑"
      },
      {
        "name": "sos",
        "char": "🆘"
      },
      {
        "name": "id",
        "char": "🆔"
      },
      {
        "name": "no_entry_sign",
        "char": "🚫"
      },
      {
        "name": "underage",
        "char": "🔞"
      },
      {
        "name": "no_entry",
        "char": "⛔"
      },
      {
        "name": "negative_squared_cross_mark",
        "char": "❎"
      },
      {
        "name": "white_check_mark",
        "char": "✅"
      },
      {
        "name": "heart_decoration",
        "char": "💟"
      },
      {
        "name": "vs",
        "char": "🆚"
      },
      {
        "name": "vibration_mode",
        "char": "📳"
      },
      {
        "name": "mobile_phone_off",
        "char": "📴"
      },
      {
        "name": "ab",
        "char": "🆎"
      },
      {
        "name": "diamond_shape_with_a_dot_inside",
        "char": "💠"
      },
      {
        "name": "ophiuchus",
        "char": "⛎"
      },
      {
        "name": "six_pointed_star",
        "char": "🔯"
      },
      {
        "name": "atm",
        "char": "🏧"
      },
      {
        "name": "chart",
        "char": "💹"
      },
      {
        "name": "heavy_dollar_sign",
        "char": "💲"
      },
      {
        "name": "currency_exchange",
        "char": "💱"
      },
      {
        "name": "x",
        "char": "❌"
      },
      {
        "name": "exclamation",
        "char": "❗"
      },
      {
        "name": "question",
        "char": "❓"
      },
      {
        "name": "grey_exclamation",
        "char": "❕"
      },
      {
        "name": "grey_question",
        "char": "❔"
      },
      {
        "name": "o",
        "char": "⭕"
      },
      {
        "name": "top",
        "char": "🔝"
      },
      {
        "name": "end",
        "char": "🔚"
      },
      {
        "name": "back",
        "char": "🔙"
      },
      {
        "name": "on",
        "char": "🔛"
      },
      {
        "name": "soon",
        "char": "🔜"
      },
      {
        "name": "arrows_clockwise",
        "char": "🔃"
      },
      {
        "name": "clock12",
        "char": "🕛"
      },
      {
        "name": "clock1",
        "char": "🕐"
      },
      {
        "name": "clock2",
        "char": "🕑"
      },
      {
        "name": "clock3",
        "char": "🕒"
      },
      {
        "name": "clock4",
        "char": "🕓"
      },
      {
        "name": "clock5",
        "char": "🕔"
      },
      {
        "name": "clock6",
        "char": "🕕"
      },
      {
        "name": "clock7",
        "char": "🕖"
      },
      {
        "name": "clock8",
        "char": "🕗"
      },
      {
        "name": "clock9",
        "char": "🕘"
      },
      {
        "name": "clock10",
        "char": "🕙"
      },
      {
        "name": "clock11",
        "char": "🕚"
      },
      {
        "name": "heavy_plus_sign",
        "char": "➕"
      },
      {
        "name": "heavy_minus_sign",
        "char": "➖"
      },
      {
        "name": "heavy_division_sign",
        "char": "➗"
      },
      {
        "name": "white_flower",
        "char": "💮"
      },
      {
        "name": "100",
        "char": "💯"
      },
      {
        "name": "radio_button",
        "char": "🔘"
      },
      {
        "name": "link",
        "char": "🔗"
      },
      {
        "name": "curly_loop",
        "char": "➰"
      },
      {
        "name": "trident",
        "char": "🔱"
      },
      {
        "name": "small_red_triangle",
        "char": "🔺"
      },
      {
        "name": "black_square_button",
        "char": "🔲"
      },
      {
        "name": "white_square_button",
        "char": "🔳"
      },
      {
        "name": "red_circle",
        "char": "🔴"
      },
      {
        "name": "large_blue_circle",
        "char": "🔵"
      },
      {
        "name": "small_red_triangle_down",
        "char": "🔻"
      },
      {
        "name": "white_large_square",
        "char": "⬜"
      },
      {
        "name": "black_large_square",
        "char": "⬛"
      },
      {
        "name": "large_orange_diamond",
        "char": "🔶"
      },
      {
        "name": "large_blue_diamond",
        "char": "🔷"
      },
      {
        "name": "small_orange_diamond",
        "char": "🔸"
      },
      {
        "name": "small_blue_diamond",
        "char": "🔹"
      }
    ]
  }
];

/** 635 across 6 groups, asserted at generation time. */
export const EMOJI_TOTAL = 635;
