-- The realtime outbox.
--
-- Replaces the 5-second `invalidate('room:data')` poll the SvelteKit room used. Events are
-- written in the SAME transaction as the mutation that caused them, so there is no window in
-- which a row is committed and its event is lost - publishing after COMMIT leaves exactly that
-- window, and "we drop an event if the process dies at the wrong microsecond" is not a
-- property worth shipping in something meant to run for ten years.
--
-- ## Why this table exists at all, given the schema is pinned
--
-- `0001_baseline.sql` stays byte-identical, so `pnpm schema:verify` and
-- `tradingroom_api::db::migrate::BASELINE_SHA256` are untouched. The baseline is the *baseline*, not a
-- ceiling: `SCHEMA-REFERENCE.md` §4 records that the schema chose CHECK constraints over
-- PostgreSQL enums precisely so value sets could be widened by forward-only migration. Adding
-- a table in `0003` is the same principle.
--
-- ## Why Postgres is also the replay log
--
-- The plan called for Redis Streams as the fan-out *and* the replay transport. Keeping the
-- replay here instead is a deliberate departure, and it is the smaller design:
--
--   * A reconnecting client resumes by asking for `seq > last_seen`. That is a single indexed
--     range scan on a table that is already the source of truth, so replay cannot disagree
--     with the data it describes - which two stores inevitably eventually do.
--   * It removes Redis from the correctness path entirely. Redis remains useful as a
--     cross-instance *wakeup* (a payload-free NOTIFY or a pubsub ping saying "room X has new
--     events"), but losing that wakeup costs latency, never an event: the next poll or the
--     next reconnect still finds everything.
--   * The plan's objections to LISTEN/NOTIFY - no replay, an 8 KB payload ceiling - were
--     objections to using it as the *transport*. As a wakeup carrying no payload, neither
--     applies.
--
-- ## The sequence
--
-- One global `BIGSERIAL`, not a counter per room. Per-room sequences would need either a
-- serialisable transaction or a row lock on a per-room counter, turning every write in a busy
-- room into a queue behind one row. A global sequence is monotonic *within* each room too,
-- which is the only property resume actually needs; it simply has gaps, and a client that
-- treats `seq` as an opaque increasing cursor rather than a counter never notices.
--
-- Note that a BIGSERIAL is allocated outside the transaction, so two concurrent writers can
-- COMMIT out of sequence order. A reader must therefore not treat "I have seen seq N" as "every
-- seq below N is durable" - `realtime::replay` handles this by trailing the read horizon, and
-- `the_sequence_is_monotonic_within_a_room` pins the property that is relied on.

CREATE TABLE IF NOT EXISTS public.room_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    seq bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    enterprise_id uuid NOT NULL,
    room_id uuid NOT NULL,
    -- What happened. A CHECK rather than a PG enum, matching the schema's own convention so
    -- the set can be widened by a later forward migration without a rewrite.
    type text NOT NULL,
    -- Who may see it. `room` is everyone in the room; `staff` is owner/moderator/presenter
    -- only; `member` is addressed to one member (`audience_member_id`).
    scope text DEFAULT 'room' NOT NULL,
    audience_member_id uuid,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    -- The member whose action produced this, when there was one. Lets a client suppress the
    -- echo of its own optimistic update.
    origin_member_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT room_events_pkey PRIMARY KEY (id),
    CONSTRAINT room_events_seq_unique UNIQUE (seq),
    CONSTRAINT room_events_payload_object_check CHECK ((jsonb_typeof(payload) = 'object'::text)),
    CONSTRAINT room_events_scope_check CHECK ((scope = ANY (ARRAY['room'::text, 'staff'::text, 'member'::text]))),
    -- A `member`-scoped event without an audience would be visible to nobody, which is a bug
    -- that would otherwise be silent. An audience on any other scope is equally confused.
    CONSTRAINT room_events_audience_check CHECK (
        (scope = 'member' AND audience_member_id IS NOT NULL)
        OR (scope <> 'member' AND audience_member_id IS NULL)
    ),
    CONSTRAINT room_events_enterprise_fk FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprises(id) ON DELETE CASCADE,
    CONSTRAINT room_events_room_fk FOREIGN KEY (room_id)
        REFERENCES public.rooms(id) ON DELETE CASCADE,
    CONSTRAINT room_events_origin_fk FOREIGN KEY (origin_member_id)
        REFERENCES public.room_members(id) ON DELETE SET NULL,
    CONSTRAINT room_events_audience_fk FOREIGN KEY (audience_member_id)
        REFERENCES public.room_members(id) ON DELETE CASCADE
);

-- The resume query, and the only access pattern: "everything in this room after seq N".
CREATE INDEX IF NOT EXISTS room_events_tenant_room_seq_idx
    ON public.room_events USING btree (enterprise_id, room_id, seq);

-- Retention sweep support: delete by age without scanning the table.
CREATE INDEX IF NOT EXISTS room_events_created_at_idx
    ON public.room_events USING btree (created_at);

-- ── Tenancy ────────────────────────────────────────────────────────────────
--
-- The same ENABLE + FORCE + policy shape as the other 20 tenant-scoped tables. FORCE matters:
-- without it the *owner* would bypass the policy, and migrations and admin sessions run as the
-- owner. `tradingroom_api::db` documents the GUC contract; an unset GUC yields NULL, and
-- `enterprise_id = NULL` is never true, so a connection that forgets it sees zero rows.

ALTER TABLE public.room_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_events FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS room_events_tenant_isolation ON public.room_events;
CREATE POLICY room_events_tenant_isolation ON public.room_events
    USING (enterprise_id = NULLIF(current_setting('app.enterprise_id', true), '')::uuid)
    WITH CHECK (enterprise_id = NULLIF(current_setting('app.enterprise_id', true), '')::uuid);

GRANT SELECT, INSERT, DELETE ON public.room_events TO ptr_clone_app;

-- No UPDATE grant, deliberately. An event is a statement that something happened; editing one
-- after the fact would let the log disagree with itself, and every consumer resumes from it.

-- The baseline defines `set_updated_at`, but this table has no `updated_at` column and never
-- should: an append-only log has no update path, so there is nothing for that trigger to do.
