import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

/**
 * Generated output must not be tracked, enforced rather than agreed.
 *
 * ## Why this is a test and not a line in a style guide
 *
 * 136 files of `apps/controller/coverage/` and `.vitest-report.json` were tracked until
 * 2026-08-14. The cost was never disk. Both are rewritten by every `test:unit` run, so the working
 * tree was permanently dirty and each one was swept into whatever commit came next — on that day,
 * into six commits of unrelated room work.
 *
 * That defeats the rule this repository leans on hardest: re-read your own `git diff` like a senior
 * reviewer before saying done. A diff carrying 136 files of regenerated HTML is a diff nobody reads
 * to the bottom of, and the one real change in it is the one that goes unreviewed.
 *
 * `apps/room` never tracked its equivalents, so the standard already existed — the controller was
 * simply out of step, and nothing made it stay in step. This is that something.
 *
 * ## Scope, deliberately narrow
 *
 * Only paths that are unambiguously generated by a command in this repository. A broad sweep for
 * anything that "looks generated" would eventually fail on a legitimately tracked file and be
 * deleted for crying wolf, which is worse than not existing. `build/` is not listed for exactly
 * that reason: it is ignored, but it is also a plausible source directory name.
 */

const ROOT = `${process.cwd()}/../..`;

/** Paths written by a command here, read by nothing here. */
const GENERATED = [
  { path: 'coverage', written_by: 'vitest run --coverage' },
  { path: '.vitest-report.json', written_by: 'vitest --reporter=json --outputFile' },
  { path: 'node_modules', written_by: 'pnpm install' },
  { path: '.svelte-kit', written_by: 'vite build' }
];

/**
 * Every tracked path, once. `null` when git cannot answer at all — a release tarball or a vendored
 * copy has no `.git`, and that would otherwise make every assertion below vacuously true, which is
 * the failure mode this file exists to prevent in the first place.
 */
function trackedFiles(): string[] | null {
  try {
    const out = execFileSync('git', ['ls-files'], {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      maxBuffer: 64 * 1024 * 1024
    });
    return out.split('\n').filter(Boolean);
  } catch {
    return null;
  }
}

const TRACKED = trackedFiles();
const gitAvailable = TRACKED !== null;

/**
 * Matched on path SEGMENTS, never as a substring.
 *
 * The first version of this asked git for `*coverage*` and failed on
 * the former `audit-behavior-coverage.mjs` Room script — a hand-written source file whose NAME
 * contains the word. That is the check being wrong rather than the repository, and it is exactly the trap
 * this file's own header warns about: a sweep that cries wolf gets deleted, and then nothing is
 * guarded at all. A directory is a violation only when a whole path component equals its name.
 *
 * Kept as a pure function over a supplied list rather than reaching for `TRACKED` directly, so the
 * negative control below can exercise the RULE without needing a real file in the repository to
 * exercise it against. That distinction stopped being academic on 2026-08-15: every file under
 * `apps/room/scripts` was untracked and gitignored, which removed the last tracked path in the
 * repository whose name contains "coverage" without being a coverage directory. The control had
 * hardcoded that exact file, so it went red — correctly reporting that its subject was gone, but
 * reporting it as a failure of this repository rather than of the fixture. A control whose subject
 * can be deleted by unrelated work is a control that will eventually be deleted for crying wolf.
 */
function segmentOffenders(files: readonly string[], name: string): string[] {
  return files.filter((file) => file.split('/').includes(name));
}

function offenders(name: string): string[] {
  return segmentOffenders(TRACKED ?? [], name);
}

describe('generated output is not tracked', () => {
  it('git is answering, so the assertions below are not vacuous', () => {
    expect(gitAvailable, 'git ls-files must work for this file to mean anything').toBe(true);
    // A repository that tracks no package.json is not a repository this test understands.
    expect((TRACKED ?? []).filter((f) => f.endsWith('package.json')).length).toBeGreaterThan(0);
  });

  it.each(GENERATED)('$path is not tracked (written by $written_by)', ({ path }) => {
    const tracked = offenders(path);
    expect(tracked, `${tracked.length} generated file(s) are tracked, starting with ${tracked[0]}`).toEqual([]);
  });

  it('the segment match does not fire on a source file that merely says "coverage"', () => {
    /*
      The negative control for the check itself, kept because the broad version of it shipped for one
      run and failed on a real, honest source file. If `segmentOffenders` is ever loosened back to a
      substring match, every line below goes red.

      The fixture is the point. This asserts a property of the RULE, so it must not depend on the
      repository still happening to contain a path that demonstrates it — see the note on
      `segmentOffenders`. `audit-behavior-coverage.mjs` is named here as the case that actually
      caused this, and it no longer needs to exist for the assertion to mean what it says.
    */
    const files = [
      'apps/room/scripts/audit-behavior-coverage.mjs',
      'apps/controller/src/lib/coverage-report-parser.ts',
      'docs/test-coverage.md',
      'apps/controller/coverage/index.html'
    ];

    // The three that merely CONTAIN the word are untouched...
    expect(segmentOffenders(files, 'coverage')).not.toContain('apps/room/scripts/audit-behavior-coverage.mjs');
    expect(segmentOffenders(files, 'coverage')).not.toContain('apps/controller/src/lib/coverage-report-parser.ts');
    expect(segmentOffenders(files, 'coverage')).not.toContain('docs/test-coverage.md');

    // ...and the one where it is a whole path component is the only thing caught.
    expect(segmentOffenders(files, 'coverage')).toEqual(['apps/controller/coverage/index.html']);
  });

  it('each one is ignored, so it cannot come back by accident', () => {
    /*
      Untracking without ignoring would last exactly until the next `git add -A`, which is how the
      coverage directory arrived. Both halves or neither.
    */
    const gitignore = readFileSync(`${ROOT}/.gitignore`, 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'));

    expect(gitignore).toContain('coverage/');
    expect(gitignore).toContain('.vitest-report.json');
    expect(gitignore).toContain('node_modules/');
    expect(gitignore).toContain('.svelte-kit/');
  });
});
