<?php
/**
 * Mints a golden token using the PLUGIN'S OWN functions, under real PHP.
 *
 * The point is cross-language proof. Everything else about this integration is checked by
 * TypeScript tests that *describe* what PHP would emit; this file makes PHP actually emit it, so the
 * bytes our verifier accepts are bytes a PHP `hash_hmac` and `json_encode` really produced.
 *
 * It loads the plugin with the handful of WordPress functions the file touches at load time stubbed
 * out. It does not simulate WordPress — it only needs `tradingroom_sso_mint()` and
 * `tradingroom_sso_entitlements()`, and those are deliberately free of WordPress state.
 *
 * Deterministic on purpose: fixed secret, fixed room, fixed timestamps. The output is committed as
 * `golden-token.json` and pinned by `sso-wordpress-contract.test.ts`, so a change to either side's
 * encoding fails a test instead of a customer's login.
 *
 * Run it (no local PHP needed):
 *
 *   docker run --rm -v "$PWD/integrations/wordpress/tradingroom-sso":/app php:8.3-cli \
 *     php /app/tests/mint-golden-token.php > integrations/wordpress/tradingroom-sso/tests/golden-token.json
 *
 * @package TradingRoomSSO
 */

// The plugin refuses to load without this, which is the guard that stops a direct web request.
define( 'ABSPATH', __DIR__ );

/* WordPress functions the plugin calls at load time. No-ops: we are not booting WordPress. */
function add_action( $hook, $callback = null, $priority = 10, $args = 1 ) {}
function add_shortcode( $tag, $callback ) {}

/** Used by `tradingroom_sso_mint()`. WordPress's version is `json_encode` with its own flags. */
function wp_json_encode( $data, $options = 0, $depth = 512 ) {
	return json_encode( $data, $options, $depth );
}

/**
 * Used by `tradingroom_sso_entitlements()`.
 *
 * Returns whatever a `$GLOBALS` override supplies, which is how this harness injects the
 * memberships and products a real WooCommerce would have reported.
 */
function apply_filters( $hook, $value ) {
	return $GLOBALS['tr_filters'][ $hook ] ?? $value;
}

require_once __DIR__ . '/../tradingroom-sso.php';

$secret = 'c3aa19b0f4d7481aa9e2b6c5d8e1f0a3c3aa19b0f4d7481aa9e2b6c5d8e1f0a3';
$room   = '1001';
$issued = 1800000000;

/*
  What WooCommerce would have reported for a paid-up member.

  Routed through the plugin's own `tradingroom_sso_entitlements()` rather than hand-built, so the
  golden vector exercises its normalisation — `array_values( array_unique( … ) )`, which is what
  keeps `json_encode` emitting `[]` rather than `{}`.

  The duplicate and the blank are deliberate: they prove the de-duplication and filtering are in the
  path, and the re-indexing that follows them is exactly the step that would otherwise produce an
  object.
*/
$GLOBALS['tr_filters'] = array(
	'tradingroom_sso_memberships' => array( 'gold-annual', 'gold-annual', '  ' ),
	'tradingroom_sso_products'    => array( 'options-mastery' ),
	'tradingroom_sso_permissions' => array(),
);

$entitlements = tradingroom_sso_entitlements( 1 );

// Claim order matches the plugin's init handler exactly.
$claims = array(
	'name'        => 'Dana Reyes',
	'email'       => 'dana@example.com',
	'room'        => $room,
	'memberships' => $entitlements['memberships'],
	'products'    => $entitlements['products'],
	'permissions' => $entitlements['permissions'],
	'iat'         => $issued,
	'exp'         => $issued + TRADINGROOM_SSO_TOKEN_TTL,
);

echo wp_json_encode(
	array(
		'_comment'    => 'GENERATED by tests/mint-golden-token.php under real PHP. Do not hand-edit.',
		'phpVersion'  => PHP_VERSION,
		'secret'      => $secret,
		'room'        => $room,
		'nowSeconds'  => $issued,
		'claims'      => $claims,
		'payloadJson' => wp_json_encode( $claims ),
		'token'       => tradingroom_sso_mint( $secret, $claims ),
	),
	JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES
) . "\n";
