import { globSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { svelteCodeOf } from './source-comments';

/**
 * EVERY CUSTOM-ELEMENT HOST THE GENERATED STYLESHEET SCOPES TO IS STILL IN THE MARKUP.
 *
 * ## The failure this exists for, measured rather than imagined
 *
 * `captured-runtime-components.css` is generated from the captured stylesheet, and its own header
 * says how: *"Angular's runtime scope attributes are translated to captured custom-element hosts
 * while retaining their original cascade specificity."* So a component's styles do not live in the
 * component. They live in that sheet, selected through an ancestor:
 *
 * ```css
 * app-poll-modal .poll-panel-titlebar:not(:root) { … cursor: move; user-select: none; … }
 * ```
 *
 * Which means the ancestor is load-bearing and looks like scaffolding. Replace `<app-poll-modal>`
 * with a `<div>` — exactly the tidy-up somebody reaches for in a 6,900-line file, and a change no
 * reviewer would question — and the poll panel loses its titlebar background, its drag cursor, its
 * layout and its button boxes.
 *
 * **On 2026-08-31 that was done deliberately to see what would object. Nothing did.** `svelte-check`
 * reported *1,579 files, 0 errors, 0 warnings*; eslint was clean; every unit test passed. The
 * component still compiles, still renders, and is simply unstyled.
 *
 * `img-dimensions-contract.test.ts` found the identical trap for `app-privchat`'s avatars and named
 * it *"a real and silent failure mode"*. It guarded the four images it was about. This guards the
 * mechanism.
 *
 * ## Why a SWEEP and not one assertion per host
 *
 * Measured on the day: **thirty** custom-element ancestors are used as scopes, carrying rules
 * between them, and **twenty of the thirty were named by no test in the repository** — including
 * `app-webrtc-troubleshooter` with 64 rules and `app-user-info-modal` with 31. Writing twenty
 * assertions would leave the thirty-first to be discovered the same way the first was.
 *
 * A sweep also survives the sheet CHANGING. It is regenerated by `pnpm css:sync-captured` from a
 * SHA-256-pinned source; a regeneration that introduces a new host gets covered here without anybody
 * remembering, which is the only way a generated file can be guarded at all.
 */

const GENERATED = readFileSync('src/lib/styles/captured-runtime-components.css', 'utf8');

/**
 * Every `.svelte` file that ships, COMMENTS STRIPPED. Fixtures and tests excluded.
 *
 * ## The stripping IS the assertion, and this file's own negative control is how that was learned
 *
 * The first draft read raw text and carried two cases: that the host's name appears, and a second
 * claiming to check it *"is rendered as an ELEMENT, not merely mentioned in prose"* by requiring
 * `<app-foo` followed by whitespace, `>` or `/`.
 *
 * **Its control came back GREEN.** With `<app-presenter-cams>` replaced by a `<div>` and only the
 * component's explanatory comments left mentioning it, both cases still passed: a comment quoting
 * `<app-presenter-cams>` contains the open tag AND the `>` after it. So the case written to separate
 * markup from prose passed on prose — a test that cannot fail for its stated reason, which is worse
 * than no test, because the green is what gets believed.
 *
 * This repository's components quote the reference constantly; that is the house style, and it is
 * exactly why a raw-text check is worthless here. `svelteCodeOf` is the file kept for this, and the
 * two weak cases collapse into the one strong case below.
 */
const MARKUP = globSync('src/**/*.svelte')
  .filter((path) => !path.includes('.test.'))
  .map((path) => svelteCodeOf(readFileSync(path, 'utf8')))
  .join('\n');

/**
 * Every `app-*` element the sheet uses as the FIRST term of a selector.
 *
 * Anchored at line start, because the same names appear again inside the `:not(… :is(…))` ownership
 * lists the generator writes — those are descendants being EXCLUDED from a rule, not hosts being
 * selected on, and counting them would assert that this room renders every component the capture
 * ever had.
 */
const scopedHosts = (): string[] => {
  const found = new Set<string>();
  for (const match of GENERATED.matchAll(/^(app-[a-z0-9-]+)[\s\n]/gm)) found.add(match[1]);
  return [...found].sort();
};

describe('the generated sheet is the one this file measures', () => {
  it('still carries its generated header, so it is not a hand-edited copy', () => {
    expect(GENERATED).toContain('GENERATED FROM css/complete-app-styles.css');
    expect(GENERATED).toContain('Do not edit this file by hand; run: pnpm css:sync-captured');
  });

  it('and found hosts to check, which is what makes the sweep below mean anything', () => {
    /*
      At zero hosts every assertion here is vacuously true — the way a sweep dies quietly. The floor
      is deliberately far below the measured thirty: this asserts the REGEX still works, not the
      count, because pinning the count would fail on every legitimate regeneration.
    */
    expect(scopedHosts().length).toBeGreaterThan(20);
  });
});

describe('every scoped host is still rendered', () => {
  it('names each one that is not, rather than failing on the first', () => {
    /*
      ONE case, over comment-stripped markup, requiring an open TAG — see the note on `MARKUP` for
      why the two cases this replaced were one redundant check and one that could not fail.

      Reported as a LIST, so a single run says everything that is wrong. A loop of `expect`s stops at
      the first failure and hides the rest, turning one fix into as many runs as there are defects.
    */
    const absent = scopedHosts().filter((host) => !new RegExp(`<${host}[\\s>/]`).test(MARKUP));
    expect(
      absent,
      'these elements are selected on by the generated stylesheet and rendered by nothing: ' +
        'their rules match no element, so those components ship unstyled and silently'
    ).toEqual([]);
  });
});

describe('the two hosts whose absence was measured, pinned by name', () => {
  /*
    A sweep is only as good as the belief that its subject matters, so the two with the most rules
    behind them are also named individually. If somebody ever narrows the sweep, these still fail.
  */
  it('app-poll-modal — 17 rules, including the titlebar s drag affordance', () => {
    expect(MARKUP).toContain('<app-poll-modal');
    expect(GENERATED).toContain('app-poll-modal .poll-panel-titlebar:not(:root) {');
  });

  it('app-webrtc-troubleshooter — 64 rules, the largest scoped block in the sheet', () => {
    expect(MARKUP).toContain('<app-webrtc-troubleshooter');
    expect(GENERATED).toContain('app-webrtc-troubleshooter ');
  });
});
